module StaticPagesHelper
    def subject_title    #絶対もっと短く書ける。
        if @subject == "constitution"
            "憲法"
        elsif @subject == "civil_law"
            "民法"
        elsif @subject == "criminal_law"
            "刑法"
        elsif @subject == "civil_procedure_law"
            "民訴"
        elsif @subject == "criminal_procedure_law"
            "刑訴"
        elsif @subject == "administrative_law"
            "行政法"
        elsif @subject == "commercial_law"
            "商法"
        elsif @subject == "bankruptcy_law"
            "倒産法"
        elsif @subject == "tax_law"
            "租税法"
        elsif @subject == "economic_law"
            "経済法"
        elsif @subject == "intellectual_property_law"
            "知的財産法"
        elsif @subject == "labor_law"
            "労働法"
        elsif @subject == "environmental_law"
            "環境法"
        elsif @subject == "international_private_law"
            "国際私法"
        elsif @subject == "international_public_law"
            "国際公法"
        end
      end
end
